version: '3.7'
services:
  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: krya
      MONGO_INITDB_USERNAME: user
      MONGO_INITDB_PASSWORD: user
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db